name: dalil_project
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.7
  internet_connection_checker: ^3.0.1
  get_it: ^8.0.3
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  sizer: ^3.0.5
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  
  fonts:
    - family: MaShanZheng
      fonts:
        - asset: assets/fonts/MaShanZheng-Regular.ttf
    - family: ArabicTypesetting
      fonts:
        - asset: assets/fonts/arabic_typesetting_regular.ttf
  assets:
    - assets/images/